### PR TITLE
fix: padded block configuration that causes ESLint v7 to fail

### LINKED ISSUE #1: Incompatible with ESlint v7
## Description

Using this plugin with ESLint v7 results in a validation error. Here is the following output when linting with v7.3.1:

```
Oops! Something went wrong! :(

ESLint: 7.3.1

Error: .eslintrc.js » plugin:@newrelic/newrelic/react » /Users/jmiller/code/developer-website/node_modules/@newrelic/eslint-plugin-newrelic/lib/config/core.js » /Users/jmiller/code/developer-website/node_modules/@newrelic/eslint-plugin-newrelic/lib/config/rules/stylistic-issues.js:
        Configuration for rule "padded-blocks" is invalid:
        Value {"blocks":"never","classes":"never","switches":"never","allowSingleLineBlocks":true} should NOT have additional properties.

    at validateRuleOptions (/Users/jmiller/code/developer-website/node_modules/eslint/lib/shared/config-validator.js:132:19)
    at /Users/jmiller/code/developer-website/node_modules/eslint/lib/shared/config-validator.js:187:9
    at Array.forEach (<anonymous>)
    at validateRules (/Users/jmiller/code/developer-website/node_modules/eslint/lib/shared/config-validator.js:184:30)
    at validateConfigArray (/Users/jmiller/code/developer-website/node_modules/eslint/lib/shared/config-validator.js:312:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/jmiller/code/developer-website/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:464:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/jmiller/code/developer-website/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:275:21)
    at FileEnumerator._iterateFilesRecursive (/Users/jmiller/code/developer-website/node_modules/eslint/lib/cli-engine/file-enumerator.js:467:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/jmiller/code/developer-website/node_modules/eslint/lib/cli-engine/file-enumerator.js:287:49)
```

## Steps to Reproduce

Upgrade a repo with ESLint to v7.3 and use this plugin. Lint the repo and you'll see the above.

## Expected Behaviour

ESLint does not error out.

## Relevant Logs / Console output

See above

## Your Environment

```
ESLint v7.3.1
eslint-plugin-newrelic v0.3.0
```

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #1 

## Description

Fix rule that causes ESLint v7 to fail due to rule validation checks.

### CODE REVIEW

File: lib/config/rules/stylistic-issues.js [hunk 1]
```diff
@@ -364,9 +364,6 @@ module.exports = {
       'error',
       'never',
       {
-        blocks: 'never',
-        classes: 'never',
-        switches: 'never',
         allowSingleLineBlocks: true
       }
     ],
```
Comment (jbeveland27) [inline lib/config/rules/stylistic-issues.js:369]: I think instead of removing this rule, it might be more appropriate to update it to match the new [rule syntax](https://eslint.org/docs/rules/padded-blocks) like below:

```
'padded-blocks': [
  'error',
  {
    blocks: 'never',
    classes: 'never',
    switches: 'never',
  }, {
    allowSingleLineBlocks: true,
  }
],
```

I tested this with v7.4.0 and it seems to work. Thoughts?

Comment (jerelmiller) [reply lib/config/rules/stylistic-issues.js:369]: I must have missed that new syntax. Thanks for letting me know about it.

I'd be happy to update this to use the newer syntax so that we maintain the same set of rules as before. Do you know if this change is compatible with eslint v6 by chance?

Comment (jbeveland27) [reply lib/config/rules/stylistic-issues.js:369]: It looks like it would be: https://eslint.org/docs/6.0.0/rules/padded-blocks

Wouldn't hurt to test though. I'll see if I can do that quick.

Comment (jerelmiller) [reply lib/config/rules/stylistic-issues.js:369]: I've always wondered how to get access to docs in older versions 😆 . Thanks for pointing me to that! Seems v7 got stricter about validating the rule configuration, so I'm not surprised we haven't seen this issue before.

Comment (jerelmiller) [reply lib/config/rules/stylistic-issues.js]: Addressed in a561c61

Comment (jbeveland27) [reply lib/config/rules/stylistic-issues.js]: Good news - seems to work in v6.8.0 just fine!
